sudo: required
dist: trusty
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ROS_DISTRO="indigo"
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=.travis.rosinstall
  matrix:
    - ROS_REPO=ros
install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh 
